version: "3.9"

services:
  devapi:
    build:
      context: .
      dockerfile: devapi.Dockerfile
    container_name: securewipe-devapi
    restart: unless-stopped
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./tools:/app/tools:ro
      - ./data:/app/data
      - ./private_prod.pem:/app/private_prod.pem:ro

  verifier:
    build:
      context: .
      dockerfile: verifier.Dockerfile
    container_name: securewipe-verifier
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./verifier:/app/verifier:ro
      - ./data:/app/data
      - ./public.pem:/app/public.pem:ro

  nginx:
    image: nginx:stable
    container_name: securewipe-nginx
    restart: unless-stopped
    depends_on:
      - devapi
      - verifier
    ports:
      - "8080:80"  # mapped to 8080 on host for local dev
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  redis:
    image: redis:7-alpine
    container_name: securewipe-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
