services:
  - type: web
    name: securewipe-devapi
    env: docker
    plan: free
    dockerfilePath: ./devapi.Dockerfile
    dockerContext: .
    envVars:
      - key: DEV_API_JWT_SECRET
        sync: false
      - key: SECUREWIPE_OPERATOR_PIN
        sync: false
      - key: VERIFIER_DB_URL
        value: sqlite:///data/verifier_receipts.db
      - key: SIGNING_KEY_PATH
        value: /app/private_prod.pem
      - key: RATE_LIMIT_STORAGE
        value: rediss://securewipe-redis:6379
      - key: SMTP_SERVER
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: EMAIL_FROM
        sync: false
    autoDeploy: true

  - type: web
    name: securewipe-verifier
    env: docker
    plan: free
    dockerfilePath: ./verifier.Dockerfile
    dockerContext: .
    envVars:
      - key: VERIFIER_API_KEY
        sync: false
      - key: VERIFIER_DB_URL
        value: sqlite:///data/verifier_receipts.db
      - key: RATE_LIMIT_STORAGE
        value: rediss://securewipe-redis:6379
    autoDeploy: true

  - type: web
    name: securewipe-frontend
    env: docker
    plan: free
    dockerfilePath: ./docker/nginx.Dockerfile
    dockerContext: .
    envVars: []
    autoDeploy: true

  - type: redis
    name: securewipe-redis
    ipAllowList: [] # allow all internal services
    plan: free
